### ISSUE TITLE
[FEAT] 핫트렌딩 성별, 나이에 따른 필터 추가

### ISSUE THREAD

**Issue by shhyunn** [SingSongSangSong/SingSong-Frontend#26]
## Feature Issue
기존 단일 데이터에 대한 핫트렌딩 인기차트에 성별 (All, 남, 여) 및 나이(All, 10대, 20대, 30대, 4대)에 따른 인기차트를 제공한다.
## To-Do
- [x] 성별에 따른 데이터 수정
- [x] 연령대에 따른 데이터 수정
- [x] 전체적인 디자인 수정

## References
.
