### ISSUE TITLE
[FEAT] 설정 화면 디자인 수정 및 닉네임 변경 기능 추가

### ISSUE THREAD

**Issue by shhyunn** [SingSongSangSong/SingSong-Frontend#30]
## 💡 Feature Issue
설정 페이지의 전반적인 디자인을 수정합니다. 또한, 닉네임 정보를 표시하고, 원한다면 사용자가 변경 가능하도록 기능을 추가합니다.

## ✔️ To-Do
- [x] 닉네임 정보 표시
- [x] 닉네임 변경 가능한 로직 추가
- [x] 설정 화면 전반 디자인 수정

## 🗒️ References
.
