### ISSUE TITLE
[FEAT] 성별 / 연령대 입력 시 디자인 수정 및 이용약관 동의 추가

### ISSUE THREAD

**Issue by shhyunn** [SingSongSangSong/SingSong-Frontend#32]
## 💡 Feature Issue
로그인 후 성별과 연령대를 입력받을 때, 기존 모달에서 진행되던 과정을 새로운 스크린으로 이동하여 UI/UX를 개선한다.
또한, 추가적인 정보를 입력받고 이용하는 것에 대한 개인정보 동의를 받는 과정을 추가한다.

## ✔️ To-Do
- [x] 모달에서 스크린으로 변경 및 UI 수정
- [x] 로그인 및 약관 화면으로 분리하여 로그인 로직 수정
- [x] 개인정보 동의 세부 약관 추가

## 🗒️ References
.
