### ISSUE TITLE
[FEAT] FCM 알람 적용하기

### ISSUE THREAD

**Issue by shhyunn** [SingSongSangSong/SingSong-Frontend#42]
## 💡 Feature Issue
Firebase FCM 알람 적용하기 위한 세팅을 한다.

## ✔️ To-Do
- [x] FCM 설정 for android
- [ ] FCM 설정 for ios
- [ ] 알람 권한 설정 for ios

## 🗒️ References
https://notifee.app/react-native/docs/integrations/fcm
